# Generated by Django 5.1.6 on 2025-03-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='CourseTitle',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='Department',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='Instructor',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
