# Generated by Django 5.1.6 on 2025-03-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0002_remove_post_content_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CourseTable',
        ),
    ]
