# Generated by Django 5.1.6 on 2025-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0003_rename_post_coursetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='CourseTitle',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='Department',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='Instructor',
            field=models.CharField(default='', max_length=150),
        ),
    ]
