# Generated by Django 5.1.6 on 2025-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0004_alter_coursetable_coursetitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetable',
            name='CourseTitle',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='Department',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursetable',
            name='Instructor',
            field=models.CharField(max_length=150),
        ),
    ]
